export const siteConfig = {
  name: "Aditya Agarwal",
  tagline: "AI/ML enthusiast — building intelligent systems and innovative solutions.",
  role: "AI/ML Developer • Flutter Developer • IoT Engineer",
  contact: {
    email: "aditya1si22cs009@gmail.com",
    phone: "+91 7003436522",
    location: "Tumkur, Karnataka, India",
  },
  socials: {
    linkedin: "https://www.linkedin.com/in/agarwal7632",
    github: "https://github.com/A-Agarwal76",
  },
  education: {
    institute: "Siddaganga Institute of Technology",
    location: "Tumkur, Karnataka",
    degree: "B.E. in Computer Science",
    graduation: "2026",
  },
  skills: {
    languages: ["Python", "Java", "C", "Dart", "Flutter"],
    frameworks: [
      "Supervised & Unsupervised Learning",
      "Model Training & Evaluation",
      "Feature Engineering",
      "RAG",
      "AI Agents",
      "Multi-step Reasoning",
      "Agent Workflows",
      "GRPO",
      "Transformers",
      "Embeddings",
      "Prompt Engineering",
      "Function Calling",
      "Vector Databases",
      "NumPy",
      "Pandas",
      "Scikit-learn",
      "Hugging Face Transformers",
      "CrewAI",
      "LangChain",
      "FastAPI",
      "Git",
      "GitHub",
    ],
    fundamentals: [
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Database Management Systems",
      "Operating Systems",
    ],
  },
  projectsPage: {
    title: "Selected Projects",
    quote: "I build intelligent systems that solve real-world problems through AI, IoT, and innovative technology.",
  },
  projects: [
    {
      title: "CoWriter - AI Writing Assistant",
      description: "An AI-powered writing assistant that helps users generate, refine, and enhance written content using advanced language models and intelligent suggestions.",
      stack: ["Python", "AI/ML", "NLP", "Streamlit"],
      link: "https://github.com/A-Agarwal76/cowriter",
      demo: undefined,
      image: "/images/cowriter.png",
      facts: [
        "AI-driven content generation and refinement",
        "Intelligent writing suggestions and enhancements",
        "Streamlit-based interactive user interface",
      ],
    },
    {
      title: "Trading MCP Server",
      description: "A Model Context Protocol server for trading and financial data, enabling AI agents to interact with real-time market data, execute trades, and analyze financial instruments.",
      stack: ["TypeScript", "MCP", "Node.js", "Financial APIs"],
      link: "https://github.com/A-Agarwal76/trading_mcp",
      demo: undefined,
      image: "/images/trading_mcp.png",
      facts: [
        "MCP protocol for AI agent trading integration",
        "Real-time market data and financial analysis",
        "TypeScript-based modular server architecture",
      ],
    },
    {
      title: "Misaligned - AI Alignment Testing",
      description: "A tool for testing and evaluating AI model alignment, detecting misaligned behaviors, and scoring safety metrics across different model responses.",
      stack: ["Python", "AI/ML", "LLM Evaluation", "Safety Testing"],
      link: "https://github.com/A-Agarwal76/misaligned",
      demo: undefined,
      image: "/images/misaligned.png",
      facts: [
        "AI alignment and safety evaluation framework",
        "Automated misalignment detection and scoring",
        "Comprehensive model behavior analysis",
      ],
    },
    {
      title: "Red Team vs Blue Team Security Simulator",
      description: "A simulated adversarial attack-defense environment featuring a multi-round attack, detect, and mitigate loop. Utilizes a state machine environment and a RAG agent acting as a referee to score breach logs, detection latency, and overall performance.",
      stack: ["Python", "Streamlit", "RAG Agent", "State Machine"],
      link: "https://github.com/A-Agarwal76/redVsBlueTeam",
      demo: undefined,
      image: "/images/redvsblue.png",
      facts: [
        "Adversarial attack-defense cycle simulation",
        "Multi-round detection and mitigation with scoring",
        "Referee RAG agent with structured event logs",
      ],
    },
    {
      title: "AI Food Assistant",
      description: "An AI-powered food assistant that helps users discover recipes, get nutritional information, and receive personalized meal recommendations based on dietary preferences.",
      stack: ["Python", "AI/ML", "Streamlit", "NLP"],
      link: "https://github.com/A-Agarwal76/AI_Food_Asistant",
      demo: undefined,
      image: "/images/ai_food.png",
      facts: [
        "AI-driven personalized meal recommendations",
        "Nutritional analysis and dietary tracking",
        "Natural language recipe search and discovery",
      ],
    },
    {
      title: "AI Therapist Mobile App",
      description: "A cross-platform mobile application for mental health support powered by AI, built with Flutter and Dart for a smooth, native-like experience with real-time conversations.",
      stack: ["Flutter", "Dart", "Firebase", "AI/ML"],
      link: "https://github.com/A-Agarwal76/AI_Therapist",
      demo: undefined,
      image: "/images/ai_therapist_app.png",
      facts: [
        "Cross-platform mobile app with Flutter",
        "AI-powered mental health conversations",
        "Firebase real-time backend integration",
      ],
    },
  ],
  achievements: [
    { title: "IoT Track Winner at NMIT HACKS 2024", subtitle: "48-hour national-level hackathon", date: "2024" },
    { title: "Metadom Hackathon", subtitle: "3rd Place (organized by Metadom.AI, sponsored by Google Cloud)", date: "2024" },
    { title: "Browse Hyperthon", subtitle: "Winner - 6-hour national-level hackathon", date: "2025" },
    { title: "AI Agents Hackathon by August AI", subtitle: "Participant (sponsored by Microsoft Startups and Sarvam AI)", date: "2024" },
    { title: "Mercuria Hackathon", subtitle: "Top 10 Finalist", date: "2024" },
    { title: "Hackathons & Robotics Competitions", subtitle: "10+ events participated", date: "2022-2026" },
  ],

  about: {
    profileImage: "/images/Travel1.jpeg",
    intro:
      "I'm passionate about AI/ML, IoT, and mobile development. I love building intelligent systems that solve real-world problems and participating in hackathons to push the boundaries of technology. Beyond code, I'm an explorer at heart — whether it's trekking through tea plantations, savoring street food, or getting lost in a good book.",
    hobbies: [
      {
        title: "Traveling",
        description: "Exploring new places, cultures, and stunning landscapes across India and beyond.",
        image: "/images/Travel2.jpeg",
        emoji: "✈️",
        color: "emerald",
      },

      {
        title: "Reading Books",
        description: "Diving into technology, philosophy, and fiction to broaden perspectives and fuel creativity.",
        image: "/images/hackathons.jpg",
        emoji: "📚",
        color: "blue",
      },
      {
        title: "Hackathons",
        description: "Participating in national and international hackathons to solve real-world problems with code.",
        image: "/images/WhatsApp%20Image%202026-06-22%20at%2011.34.30%20PM.jpeg",
        emoji: "🏆",
        color: "purple",
      },
      {
        title: "Robotics & IoT",
        description: "Building and programming robots, designing networked systems, and pushing hardware boundaries.",
        image: "/images/WhatsApp%20Image%202026-06-22%20at%2011.37.05%20PM.jpeg",
        emoji: "🤖",
        color: "cyan",
      },
      {
        title: "Teaching & Mentoring",
        description: "Sharing knowledge through workshops, brainstorming sessions, and mentoring peers in tech.",
        image: "/images/WhatsApp%20Image%202026-06-22%20at%2011.36.20%20PM.jpeg",
        emoji: "🧠",
        color: "pink",
      },
    ],
    communities: [
      {
        name: "AI Brewery",
        role: "Co-Founder and Vice-Chair",
        image: "/images/HackathonOrg.jpeg",
        highlights: [
          "Leading young and enthusiastic minds who want to make cutting edge AI Agents.",
          "Involved in participating in Hackathons and Company events all across India.",
        ],
      },
      {
        name: "Club of Robotics, SIT",
        role: "App Lead and Expedition Lead",
        image: "/images/WorkshopOrg.jpeg",
        highlights: [
          "Designed and deployed networked robotic systems using wireless communication.",
          "Organized ROBOCOR'24 & '25, a national-level robotics event with 1000+ participants.",
        ],
      },
    ],
  },
}
